package com.google.android.gms.ads.internal.flag;

import defpackage.fmle;
import defpackage.fmlh;
import defpackage.fmlk;
import defpackage.fmln;
import defpackage.fmlq;
import defpackage.fmlt;
import defpackage.fmlw;
import defpackage.fmlz;
import defpackage.fmmc;
import defpackage.fmmf;
import defpackage.fmmi;
import defpackage.fmml;
import defpackage.fmmo;
import defpackage.fmmr;
import defpackage.fmmu;
import defpackage.fmna;
import defpackage.fmng;
import defpackage.fmnj;
import defpackage.fmnm;
import defpackage.fmnp;
import defpackage.fmns;
import defpackage.fmnv;
import defpackage.fmny;
import defpackage.fmob;
import defpackage.fmoe;
import defpackage.fmoh;
import defpackage.fmok;
import defpackage.fmoq;
import defpackage.fmot;
import defpackage.fmow;
import defpackage.fmoz;
import defpackage.fmpc;
import defpackage.fmpf;
import defpackage.fmpi;
import defpackage.fmpl;
import defpackage.fmpr;
import defpackage.fmpu;
import defpackage.fmpx;

/* compiled from: :com.google.android.gms@251864004@25.18.64 (040400-758020094) */
/* loaded from: classes2.dex */
public final class b {
    public static void a(z zVar) {
        fmlt fmltVar = fmlt.a;
        fmltVar.lK().b();
        zVar.b("gads:sequential_cache_delay_to_load_seconds", fmltVar.lK().a());
        fmle.a.lK().c();
        zVar.d("gads:doritos_refresh_network_migration:enabled", fmle.d());
        zVar.b("gads:timeout_for_doritos_refresh:millis", fmle.b());
        fmnj fmnjVar = fmnj.a;
        fmnjVar.lK().l();
        zVar.c("gads:gma_attestation:click:macro_string", fmnjVar.lK().c());
        zVar.c("gads:gma_attestation:click:query_param", fmnjVar.lK().d());
        zVar.b("gads:gma_attestation:click:timeout", fmnjVar.lK().a());
        zVar.d("gads:gma_attestation:click:enable", fmnjVar.lK().e());
        zVar.b("gads:gma_attestation:click:enable_dynamite_version", fmnjVar.lK().b());
        zVar.d("gads:gma_attestation:click:qualification:enable", fmnjVar.lK().f());
        zVar.d("gads:gma_attestation:image_hash", fmnjVar.lK().g());
        zVar.d("gads:gma_attestation:impression:enable", fmnjVar.lK().h());
        zVar.d("gads:gma_attestation:request:enable_javascript", fmnjVar.lK().i());
        zVar.d("gads:gma_attestation:request:enable", fmnjVar.lK().j());
        zVar.d("gads:gma_attestation:click:report_error", fmnjVar.lK().k());
        fmlh fmlhVar = fmlh.a;
        fmlhVar.lK().e();
        zVar.d("gads:afs:csa_send_tcf_data", fmlhVar.lK().d());
        zVar.c("gads:afs:csa_tcf_data_to_collect", fmlhVar.lK().a());
        zVar.c("gads:afs:csa_webview_custom_domain_param_key", fmlhVar.lK().b());
        zVar.c("gads:afs:csa_webview_static_file_path", fmlhVar.lK().c());
        fmmf fmmfVar = fmmf.a;
        fmmfVar.lK().g();
        zVar.b("gads:content_age_weight", fmmfVar.lK().a());
        zVar.d("gads:enable_content_fetching", fmmfVar.lK().f());
        zVar.b("gads:fingerprint_number", fmmfVar.lK().b());
        zVar.b("gads:content_length_weight", fmmfVar.lK().c());
        zVar.b("gads:min_content_len", fmmfVar.lK().d());
        zVar.b("gads:sleep_sec", fmmfVar.lK().e());
        fmmu fmmuVar = fmmu.a;
        fmmuVar.lK().c();
        zVar.d("gads:debug_logging_feature:enable", fmmu.c());
        zVar.d("gads:debug_logging_feature:intercept_web_view", fmmuVar.lK().b());
        fmmr fmmrVar = fmmr.a;
        fmmrVar.lK().d();
        zVar.d("gad:force_dynamite_loading_enabled", fmmrVar.lK().a());
        zVar.d("gad:force_local_loading_enabled", fmmrVar.lK().b());
        zVar.d("gads:sdk_csi_write_to_file", fmmrVar.lK().c());
        fmlw fmlwVar = fmlw.a;
        fmlwVar.lK().i();
        zVar.b("gads:app_permissions_caching_expiry_ms:expiry", fmlwVar.lK().a());
        zVar.b("gads:audio_caching_expiry_ms:expiry", fmlwVar.lK().b());
        zVar.b("gads:battery_caching_expiry_ms:expiry", fmlwVar.lK().c());
        zVar.b("gads:device_info_caching_expiry_ms:expiry", fmlwVar.lK().d());
        zVar.b("gads:hsdp_caching_expiry_ms:expiry", fmlwVar.lK().e());
        zVar.b("gads:memory_caching_expiry_ms:expiry", fmlwVar.lK().f());
        zVar.b("gads:sdk_environment_caching_expiry_ms:expiry", fmlwVar.lK().g());
        zVar.b("gads:telephony_caching_expiry_ms:expiry", fmlwVar.lK().h());
        fmlz fmlzVar = fmlz.a;
        fmlzVar.lK().c();
        zVar.d("gads:enable_gmscore_logger", fmlzVar.lK().b());
        zVar.a("gads:gmscore_logger_sampling_rate", fmlzVar.lK().a());
        fmmc fmmcVar = fmmc.a;
        fmmcVar.lK().b();
        zVar.d("gads:clearcut_log_verifier:enabled", fmmcVar.lK().a());
        fmmi fmmiVar = fmmi.a;
        fmmiVar.lK().k();
        zVar.d("gads:always_enable_crash_loop_counter_v2:enabled", fmmiVar.lK().c());
        zVar.d("gads:crash_loop_stats_signal_v2:enabled", fmmiVar.lK().d());
        zVar.d("gads:crash_without_flag_write_count_v2:enabled", fmmiVar.lK().e());
        zVar.b("gads:crash_without_write_reset_v2:count", fmmiVar.lK().a());
        zVar.d("gads:init_without_flag_write_count_v2:enabled", fmmiVar.lK().f());
        zVar.b("gads:init_without_write_reset_v2:count", fmmiVar.lK().b());
        zVar.d("gads:reset_app_settings_v2:enabled", fmmiVar.lK().g());
        zVar.d("gads:reset_counts_on_failure_service_v2:enabled", fmmiVar.lK().h());
        zVar.d("gads:reset_counts_on_local_flag_save_v2:enabled", fmmiVar.lK().i());
        zVar.d("gads:reset_counts_on_successful_service_v2:enabled", fmmiVar.lK().j());
        fmmo fmmoVar = fmmo.a;
        fmmoVar.lK().d();
        zVar.a("gads:csi_reporting_ratio", fmmoVar.lK().a());
        zVar.c("gads:sdk_csi_server", fmmoVar.lK().b());
        zVar.d("gads:enabled_sdk_csi", fmmoVar.lK().c());
        fmnp fmnpVar = fmnp.a;
        fmnpVar.lK().m();
        zVar.d("gads:disable_flag_shared_pref_listener_v2:enabled", fmnpVar.lK().b());
        zVar.d("gads:include_package_name_v2:enabled", fmnpVar.lK().c());
        zVar.d("gads:js_flags:mf", fmnpVar.lK().d());
        zVar.b("gads:js_flags:update_interval", fmnpVar.lK().a());
        zVar.d("gads:persist_js_flag:ars", fmnpVar.lK().e());
        zVar.d("gads:persist_js_flag:as", fmnpVar.lK().f());
        zVar.d("gads:persist_js_flag:scar", fmnpVar.lK().g());
        zVar.d("gads:read_local_flags_v2:enabled", fmnpVar.lK().h());
        zVar.d("gads:read_local_flags_cld_v2:enabled", fmnpVar.lK().i());
        zVar.d("gads:write_local_flags_cld_v2:enabled", fmnpVar.lK().j());
        zVar.d("gads:write_local_flags_client_v2:enabled", fmnpVar.lK().k());
        zVar.d("gads:write_local_flags_service_v2:enabled", fmnpVar.lK().l());
        fmng fmngVar = fmng.a;
        fmngVar.lK().m();
        zVar.d("gads:init:init_on_bg_thread", fmngVar.lK().a());
        zVar.d("gads:init:init_on_single_bg_thread", fmngVar.lK().b());
        zVar.d("gads:adloader_load_bg_thread", fmngVar.lK().c());
        zVar.d("gads:appopen_load_on_bg_thread", fmngVar.lK().d());
        zVar.d("gads:banner_destroy_bg_thread", fmngVar.lK().e());
        zVar.d("gads:banner_load_bg_thread", fmngVar.lK().f());
        zVar.d("gads:banner_pause_bg_thread", fmngVar.lK().g());
        zVar.d("gads:banner_resume_bg_thread", fmngVar.lK().h());
        zVar.d("gads:interstitial_load_on_bg_thread", fmngVar.lK().i());
        zVar.d("gads:persist_flags_on_bg_thread", fmngVar.lK().j());
        zVar.d("gads:query_info_bg_thread", fmngVar.lK().k());
        zVar.d("gads:rewarded_load_bg_thread", fmngVar.lK().l());
        fmnv fmnvVar = fmnv.a;
        fmnvVar.lK().b();
        zVar.d("gads:log:verbose_enabled", fmnvVar.lK().a());
        fmob fmobVar = fmob.a;
        fmobVar.lK().b();
        zVar.b("gads:parallel_rendering:max_renderers", fmobVar.lK().a());
        fmok fmokVar = fmok.a;
        fmokVar.lK().e();
        zVar.d("gads:separate_url_generation:enabled", fmokVar.lK().c());
        zVar.c("gads:google_ad_request_domains", fmokVar.lK().b());
        zVar.b("gads:url_cache:max_size", fmokVar.lK().a());
        zVar.d("gads:use_request_id_as_url_cache_key:enabled", fmokVar.lK().d());
        fmow fmowVar = fmow.a;
        fmowVar.lK().h();
        zVar.b("gads:dynamite_load:fail:sample_rate", fmowVar.lK().b());
        zVar.d("gads:report_dynamite_crash_in_background_thread", fmowVar.lK().e());
        zVar.c("gads:public_beta:traffic_multiplier", fmowVar.lK().c());
        zVar.c("gads:sdk_crash_report_class_prefix", fmowVar.lK().d());
        zVar.d("gads:sdk_crash_report_enabled", fmowVar.lK().f());
        zVar.d("gads:sdk_crash_report_full_stacktrace", fmowVar.lK().g());
        zVar.a("gads:trapped_exception_sample_rate", fmowVar.lK().a());
        fmpl fmplVar = fmpl.a;
        fmplVar.lK().d();
        zVar.b("gads:ad_loader:timeout_ms", fmplVar.lK().a());
        zVar.b("gads:rendering:timeout_ms", fmplVar.lK().b());
        zVar.b("gads:resolve_future:default_timeout_ms", fmplVar.lK().c());
        fmoh fmohVar = fmoh.a;
        fmohVar.lK().k();
        zVar.d("gads:adapter_initialization:red_button", fmohVar.lK().a());
        zVar.d("gads:adapter_settings:red_button", fmohVar.lK().b());
        zVar.d("gads:ads_service_force_stop:red_button", fmohVar.lK().c());
        zVar.d("gads:banner_refresh_sequential_caching:red_button", fmohVar.lK().d());
        zVar.d("gads:ad_serving:enabled", fmohVar.lK().e());
        zVar.d("gads:ad_preloading:enabled", fmohVar.lK().f());
        zVar.d("gads:adaptive_banner:fail_invalid_ad_size", fmohVar.lK().g());
        zVar.d("gads:sdk_use_dynamic_module", fmohVar.lK().h());
        zVar.d("gads:signal_adapters:red_button", fmohVar.lK().i());
        zVar.d("gads:use_non_templated_client_sdkcore:enabled", fmohVar.lK().j());
        fmpu fmpuVar = fmpu.a;
        fmpuVar.lK().b();
        zVar.d("gads:video:metric_reporting_enabled", fmpuVar.lK().a());
        fmna fmnaVar = fmna.a;
        fmnaVar.lK().v();
        zVar.c("gads:afs:csa:experiment_id", fmnaVar.lK().a());
        zVar.c("gads:app_index:experiment_id", fmnaVar.lK().b());
        zVar.c("gads:block_autoclicks_experiment_id", fmnaVar.lK().c());
        zVar.c("gads:sdk_core_experiment_id", fmnaVar.lK().d());
        zVar.c("gads:spam_app_context:experiment_id", fmnaVar.lK().e());
        zVar.c("gads:temporary_experiment_id:1", fmnaVar.lK().f());
        zVar.c("gads:temporary_experiment_id:10", fmnaVar.lK().g());
        zVar.c("gads:temporary_experiment_id:11", fmnaVar.lK().h());
        zVar.c("gads:temporary_experiment_id:12", fmnaVar.lK().i());
        zVar.c("gads:temporary_experiment_id:13", fmnaVar.lK().j());
        zVar.c("gads:temporary_experiment_id:14", fmnaVar.lK().k());
        zVar.c("gads:temporary_experiment_id:15", fmnaVar.lK().l());
        zVar.c("gads:temporary_experiment_id:2", fmnaVar.lK().m());
        zVar.c("gads:temporary_experiment_id:3", fmnaVar.lK().n());
        zVar.c("gads:temporary_experiment_id:4", fmnaVar.lK().o());
        zVar.c("gads:temporary_experiment_id:5", fmnaVar.lK().p());
        zVar.c("gads:temporary_experiment_id:6", fmnaVar.lK().q());
        zVar.c("gads:temporary_experiment_id:7", fmnaVar.lK().r());
        zVar.c("gads:temporary_experiment_id:8", fmnaVar.lK().s());
        zVar.c("gads:temporary_experiment_id:9", fmnaVar.lK().t());
        zVar.c("gads:corewebview:experiment_id", fmnaVar.lK().u());
        fmpf fmpfVar = fmpf.a;
        fmpfVar.lK().b();
        zVar.c("gads:pan:experiment_id", fmpfVar.lK().a());
        fmlk fmlkVar = fmlk.a;
        fmlkVar.lK().c();
        zVar.b("gads:app_index:timeout_ms", fmlkVar.lK().a());
        zVar.d("gads:app_index:without_content_info_present:enabled", fmlkVar.lK().b());
        fmny fmnyVar = fmny.a;
        fmnyVar.lK().c();
        zVar.d("gads:ad_key_enabled", fmnyVar.lK().a());
        zVar.d("gads:adshield:enable_adshield_instrumentation", fmnyVar.lK().b());
        fmoq fmoqVar = fmoq.a;
        fmoqVar.lK().c();
        zVar.d("gads:rewarded_sku:enabled", fmoqVar.lK().a());
        zVar.d("gads:rewarded_sku:override_test:enabled", fmoqVar.lK().b());
        fmot fmotVar = fmot.a;
        fmotVar.lK().c();
        zVar.c("gads:safe_browsing:api_key", fmotVar.lK().a());
        zVar.d("gads:safe_browsing:debug", fmotVar.lK().b());
        fmoz fmozVar = fmoz.a;
        fmozVar.lK().d();
        zVar.c("gads:native:engine_js_url_with_protocol", fmozVar.lK().a());
        zVar.c("gads:sdk_core_location", fmozVar.lK().b());
        zVar.c("gads:sdk_core_js_location", fmozVar.lK().c());
        fmpx fmpxVar = fmpx.a;
        fmpxVar.lK().b();
        zVar.d("gads:webview:permission:disabled", fmpxVar.lK().a());
        fmlq fmlqVar = fmlq.a;
        fmlqVar.lK().c();
        zVar.d("gads:auto_location_by_dynamite", fmlqVar.lK().a());
        zVar.d("gads:auto_location_by_gmscore", fmlqVar.lK().b());
        fmnm fmnmVar = fmnm.a;
        fmnmVar.lK().c();
        zVar.d("gads:split_ad_request_traffic_by_app", fmnm.c());
        zVar.d("gads:split_doritos_traffic_from_ads_tag", fmnmVar.lK().b());
        fmns fmnsVar = fmns.a;
        fmnsVar.lK().d();
        zVar.d("gads:lite_sdk_retriever:adapter:enable", fmnsVar.lK().b());
        zVar.b("gads:lite_sdk_retriever:dynamite_version", fmnsVar.lK().a());
        zVar.d("gads:lite_sdk_retriever:version_number:enable", fmnsVar.lK().c());
        fmpi fmpiVar = fmpi.a;
        fmpiVar.lK().b();
        zVar.d("gads:signals_collection_on_service:enabled", fmpiVar.lK().a());
        fmpr fmprVar = fmpr.a;
        fmprVar.lK().i();
        zVar.d("gads:trustless_token_for_decagon:enabled", fmprVar.lK().d());
        zVar.d("gads:invalidate_token_at_refresh_start", fmprVar.lK().e());
        zVar.d("gms:expose_token_for_gma:enabled", fmpr.e());
        zVar.d("gads:referesh_rate_limit", fmpr.f());
        zVar.b("gads:timeout_for_trustless_token:millis", fmprVar.lK().a());
        zVar.d("gads:token_anonymization:enabled", fmpr.g());
        zVar.c("gads:token_anonymization_key", fmpr.d());
        zVar.b("gads:cached_token:ttl_millis", fmpr.b());
        fmml fmmlVar = fmml.a;
        fmmlVar.lK().f();
        zVar.a("gads:cui_monitoring_session_sample_rate", fmmlVar.lK().a());
        zVar.d("gads:cui_monitoring_enabled", fmmlVar.lK().b());
        zVar.d("gads:cui_monitoring_v2_enabled", fmmlVar.lK().c());
        zVar.d("gads:cui_monitoring_v3_enabled", fmmlVar.lK().d());
        zVar.d("gads:cui_monitoring_v4_enabled", fmmlVar.lK().e());
        fmln fmlnVar = fmln.a;
        fmlnVar.lK().c();
        zVar.d("gads:timeout_for_app_set_id_info_gmscore:enabled", fmlnVar.lK().b());
        zVar.b("gads:timeout_for_app_set_id_info_gmscore:millis", fmlnVar.lK().a());
        fmoe fmoeVar = fmoe.a;
        fmoeVar.lK().i();
        zVar.d("gads:delegating_web_view_client_recursion_detection:enabled", fmoeVar.lK().d());
        zVar.d("gads:paw_app_signals:document_start_js:enabled", fmoeVar.lK().e());
        zVar.d("gads:paw_app_signals:enabled", fmoeVar.lK().f());
        zVar.d("gads:paw_delegate_web_view_client:enabled", fmoeVar.lK().g());
        zVar.d("gads:paw_cache:enabled", fmoeVar.lK().h());
        zVar.b("gads:paw_cache:refresh_interval_seconds", fmoeVar.lK().a());
        zVar.b("gads:paw_cache:retry_delay_seconds", fmoeVar.lK().b());
        zVar.b("gads:paw_cache:ttl_ms", fmoeVar.lK().c());
        fmpc fmpcVar = fmpc.a;
        fmpcVar.lK().b();
        zVar.b("gads:minimum_service:version", fmpcVar.lK().a());
    }
}
