package com.google.android.gms.ads.internal.flag;

import defpackage.fjva;
import defpackage.fjvd;
import defpackage.fjvg;
import defpackage.fjvj;
import defpackage.fjvm;
import defpackage.fjvp;
import defpackage.fjvs;
import defpackage.fjvv;
import defpackage.fjvy;
import defpackage.fjwb;
import defpackage.fjwe;
import defpackage.fjwh;
import defpackage.fjwk;
import defpackage.fjwn;
import defpackage.fjwq;
import defpackage.fjww;
import defpackage.fjxc;
import defpackage.fjxf;
import defpackage.fjxi;
import defpackage.fjxl;
import defpackage.fjxo;
import defpackage.fjxr;
import defpackage.fjxu;
import defpackage.fjxx;
import defpackage.fjya;
import defpackage.fjyd;
import defpackage.fjyg;
import defpackage.fjym;
import defpackage.fjyp;
import defpackage.fjys;
import defpackage.fjyv;
import defpackage.fjyy;
import defpackage.fjzb;
import defpackage.fjze;
import defpackage.fjzh;
import defpackage.fjzn;
import defpackage.fjzq;
import defpackage.fjzt;

/* compiled from: :com.google.android.gms@251661004@25.16.61 (040400-752466036) */
/* loaded from: classes2.dex */
public final class b {
    public static void a(z zVar) {
        fjvp.a.a().b();
        zVar.b("gads:sequential_cache_delay_to_load_seconds", fjvp.a.a().a());
        fjva.a.a().c();
        zVar.d("gads:doritos_refresh_network_migration:enabled", fjva.d());
        zVar.b("gads:timeout_for_doritos_refresh:millis", fjva.b());
        fjxf.a.a().l();
        fjxf fjxfVar = fjxf.a;
        zVar.c("gads:gma_attestation:click:macro_string", fjxfVar.a().c());
        zVar.c("gads:gma_attestation:click:query_param", fjxfVar.a().d());
        zVar.b("gads:gma_attestation:click:timeout", fjxfVar.a().a());
        zVar.d("gads:gma_attestation:click:enable", fjxfVar.a().e());
        zVar.b("gads:gma_attestation:click:enable_dynamite_version", fjxfVar.a().b());
        zVar.d("gads:gma_attestation:click:qualification:enable", fjxfVar.a().f());
        zVar.d("gads:gma_attestation:image_hash", fjxfVar.a().g());
        zVar.d("gads:gma_attestation:impression:enable", fjxfVar.a().h());
        zVar.d("gads:gma_attestation:request:enable_javascript", fjxfVar.a().i());
        zVar.d("gads:gma_attestation:request:enable", fjxfVar.a().j());
        zVar.d("gads:gma_attestation:click:report_error", fjxfVar.a().k());
        fjvd.a.a().e();
        fjvd fjvdVar = fjvd.a;
        zVar.d("gads:afs:csa_send_tcf_data", fjvdVar.a().d());
        zVar.c("gads:afs:csa_tcf_data_to_collect", fjvdVar.a().a());
        zVar.c("gads:afs:csa_webview_custom_domain_param_key", fjvdVar.a().b());
        zVar.c("gads:afs:csa_webview_static_file_path", fjvdVar.a().c());
        fjwb.a.a().g();
        fjwb fjwbVar = fjwb.a;
        zVar.b("gads:content_age_weight", fjwbVar.a().a());
        zVar.d("gads:enable_content_fetching", fjwbVar.a().f());
        zVar.b("gads:fingerprint_number", fjwbVar.a().b());
        zVar.b("gads:content_length_weight", fjwbVar.a().c());
        zVar.b("gads:min_content_len", fjwbVar.a().d());
        zVar.b("gads:sleep_sec", fjwbVar.a().e());
        fjwq.a.a().c();
        zVar.d("gads:debug_logging_feature:enable", fjwq.c());
        zVar.d("gads:debug_logging_feature:intercept_web_view", fjwq.a.a().b());
        fjwn.a.a().d();
        fjwn fjwnVar = fjwn.a;
        zVar.d("gad:force_dynamite_loading_enabled", fjwnVar.a().a());
        zVar.d("gad:force_local_loading_enabled", fjwnVar.a().b());
        zVar.d("gads:sdk_csi_write_to_file", fjwnVar.a().c());
        fjvs.a.a().i();
        fjvs fjvsVar = fjvs.a;
        zVar.b("gads:app_permissions_caching_expiry_ms:expiry", fjvsVar.a().a());
        zVar.b("gads:audio_caching_expiry_ms:expiry", fjvsVar.a().b());
        zVar.b("gads:battery_caching_expiry_ms:expiry", fjvsVar.a().c());
        zVar.b("gads:device_info_caching_expiry_ms:expiry", fjvsVar.a().d());
        zVar.b("gads:hsdp_caching_expiry_ms:expiry", fjvsVar.a().e());
        zVar.b("gads:memory_caching_expiry_ms:expiry", fjvsVar.a().f());
        zVar.b("gads:sdk_environment_caching_expiry_ms:expiry", fjvsVar.a().g());
        zVar.b("gads:telephony_caching_expiry_ms:expiry", fjvsVar.a().h());
        fjvv.a.a().c();
        fjvv fjvvVar = fjvv.a;
        zVar.d("gads:enable_gmscore_logger", fjvvVar.a().b());
        zVar.a("gads:gmscore_logger_sampling_rate", fjvvVar.a().a());
        fjvy.a.a().b();
        zVar.d("gads:clearcut_log_verifier:enabled", fjvy.a.a().a());
        fjwe.a.a().k();
        fjwe fjweVar = fjwe.a;
        zVar.d("gads:always_enable_crash_loop_counter_v2:enabled", fjweVar.a().c());
        zVar.d("gads:crash_loop_stats_signal_v2:enabled", fjweVar.a().d());
        zVar.d("gads:crash_without_flag_write_count_v2:enabled", fjweVar.a().e());
        zVar.b("gads:crash_without_write_reset_v2:count", fjweVar.a().a());
        zVar.d("gads:init_without_flag_write_count_v2:enabled", fjweVar.a().f());
        zVar.b("gads:init_without_write_reset_v2:count", fjweVar.a().b());
        zVar.d("gads:reset_app_settings_v2:enabled", fjweVar.a().g());
        zVar.d("gads:reset_counts_on_failure_service_v2:enabled", fjweVar.a().h());
        zVar.d("gads:reset_counts_on_local_flag_save_v2:enabled", fjweVar.a().i());
        zVar.d("gads:reset_counts_on_successful_service_v2:enabled", fjweVar.a().j());
        fjwk.a.a().d();
        fjwk fjwkVar = fjwk.a;
        zVar.a("gads:csi_reporting_ratio", fjwkVar.a().a());
        zVar.c("gads:sdk_csi_server", fjwkVar.a().b());
        zVar.d("gads:enabled_sdk_csi", fjwkVar.a().c());
        fjxl.a.a().m();
        fjxl fjxlVar = fjxl.a;
        zVar.d("gads:disable_flag_shared_pref_listener_v2:enabled", fjxlVar.a().b());
        zVar.d("gads:include_package_name_v2:enabled", fjxlVar.a().c());
        zVar.d("gads:js_flags:mf", fjxlVar.a().d());
        zVar.b("gads:js_flags:update_interval", fjxlVar.a().a());
        zVar.d("gads:persist_js_flag:ars", fjxlVar.a().e());
        zVar.d("gads:persist_js_flag:as", fjxlVar.a().f());
        zVar.d("gads:persist_js_flag:scar", fjxlVar.a().g());
        zVar.d("gads:read_local_flags_v2:enabled", fjxlVar.a().h());
        zVar.d("gads:read_local_flags_cld_v2:enabled", fjxlVar.a().i());
        zVar.d("gads:write_local_flags_cld_v2:enabled", fjxlVar.a().j());
        zVar.d("gads:write_local_flags_client_v2:enabled", fjxlVar.a().k());
        zVar.d("gads:write_local_flags_service_v2:enabled", fjxlVar.a().l());
        fjxc.a.a().m();
        fjxc fjxcVar = fjxc.a;
        zVar.d("gads:init:init_on_bg_thread", fjxcVar.a().a());
        zVar.d("gads:init:init_on_single_bg_thread", fjxcVar.a().b());
        zVar.d("gads:adloader_load_bg_thread", fjxcVar.a().c());
        zVar.d("gads:appopen_load_on_bg_thread", fjxcVar.a().d());
        zVar.d("gads:banner_destroy_bg_thread", fjxcVar.a().e());
        zVar.d("gads:banner_load_bg_thread", fjxcVar.a().f());
        zVar.d("gads:banner_pause_bg_thread", fjxcVar.a().g());
        zVar.d("gads:banner_resume_bg_thread", fjxcVar.a().h());
        zVar.d("gads:interstitial_load_on_bg_thread", fjxcVar.a().i());
        zVar.d("gads:persist_flags_on_bg_thread", fjxcVar.a().j());
        zVar.d("gads:query_info_bg_thread", fjxcVar.a().k());
        zVar.d("gads:rewarded_load_bg_thread", fjxcVar.a().l());
        fjxr.a.a().b();
        zVar.d("gads:log:verbose_enabled", fjxr.a.a().a());
        fjxx.a.a().b();
        zVar.b("gads:parallel_rendering:max_renderers", fjxx.a.a().a());
        fjyg.a.a().e();
        fjyg fjygVar = fjyg.a;
        zVar.d("gads:separate_url_generation:enabled", fjygVar.a().c());
        zVar.c("gads:google_ad_request_domains", fjygVar.a().b());
        zVar.b("gads:url_cache:max_size", fjygVar.a().a());
        zVar.d("gads:use_request_id_as_url_cache_key:enabled", fjygVar.a().d());
        fjys.a.a().h();
        fjys fjysVar = fjys.a;
        zVar.b("gads:dynamite_load:fail:sample_rate", fjysVar.a().b());
        zVar.d("gads:report_dynamite_crash_in_background_thread", fjysVar.a().e());
        zVar.c("gads:public_beta:traffic_multiplier", fjysVar.a().c());
        zVar.c("gads:sdk_crash_report_class_prefix", fjysVar.a().d());
        zVar.d("gads:sdk_crash_report_enabled", fjysVar.a().f());
        zVar.d("gads:sdk_crash_report_full_stacktrace", fjysVar.a().g());
        zVar.a("gads:trapped_exception_sample_rate", fjysVar.a().a());
        fjzh.a.a().d();
        fjzh fjzhVar = fjzh.a;
        zVar.b("gads:ad_loader:timeout_ms", fjzhVar.a().a());
        zVar.b("gads:rendering:timeout_ms", fjzhVar.a().b());
        zVar.b("gads:resolve_future:default_timeout_ms", fjzhVar.a().c());
        fjyd.a.a().k();
        fjyd fjydVar = fjyd.a;
        zVar.d("gads:adapter_initialization:red_button", fjydVar.a().a());
        zVar.d("gads:adapter_settings:red_button", fjydVar.a().b());
        zVar.d("gads:ads_service_force_stop:red_button", fjydVar.a().c());
        zVar.d("gads:banner_refresh_sequential_caching:red_button", fjydVar.a().d());
        zVar.d("gads:ad_serving:enabled", fjydVar.a().e());
        zVar.d("gads:ad_preloading:enabled", fjydVar.a().f());
        zVar.d("gads:adaptive_banner:fail_invalid_ad_size", fjydVar.a().g());
        zVar.d("gads:sdk_use_dynamic_module", fjydVar.a().h());
        zVar.d("gads:signal_adapters:red_button", fjydVar.a().i());
        zVar.d("gads:use_non_templated_client_sdkcore:enabled", fjydVar.a().j());
        fjzq.a.a().b();
        zVar.d("gads:video:metric_reporting_enabled", fjzq.a.a().a());
        fjww.a.a().v();
        fjww fjwwVar = fjww.a;
        zVar.c("gads:afs:csa:experiment_id", fjwwVar.a().a());
        zVar.c("gads:app_index:experiment_id", fjwwVar.a().b());
        zVar.c("gads:block_autoclicks_experiment_id", fjwwVar.a().c());
        zVar.c("gads:sdk_core_experiment_id", fjwwVar.a().d());
        zVar.c("gads:spam_app_context:experiment_id", fjwwVar.a().e());
        zVar.c("gads:temporary_experiment_id:1", fjwwVar.a().f());
        zVar.c("gads:temporary_experiment_id:10", fjwwVar.a().g());
        zVar.c("gads:temporary_experiment_id:11", fjwwVar.a().h());
        zVar.c("gads:temporary_experiment_id:12", fjwwVar.a().i());
        zVar.c("gads:temporary_experiment_id:13", fjwwVar.a().j());
        zVar.c("gads:temporary_experiment_id:14", fjwwVar.a().k());
        zVar.c("gads:temporary_experiment_id:15", fjwwVar.a().l());
        zVar.c("gads:temporary_experiment_id:2", fjwwVar.a().m());
        zVar.c("gads:temporary_experiment_id:3", fjwwVar.a().n());
        zVar.c("gads:temporary_experiment_id:4", fjwwVar.a().o());
        zVar.c("gads:temporary_experiment_id:5", fjwwVar.a().p());
        zVar.c("gads:temporary_experiment_id:6", fjwwVar.a().q());
        zVar.c("gads:temporary_experiment_id:7", fjwwVar.a().r());
        zVar.c("gads:temporary_experiment_id:8", fjwwVar.a().s());
        zVar.c("gads:temporary_experiment_id:9", fjwwVar.a().t());
        zVar.c("gads:corewebview:experiment_id", fjwwVar.a().u());
        fjzb.a.a().b();
        zVar.c("gads:pan:experiment_id", fjzb.a.a().a());
        fjvg.a.a().c();
        fjvg fjvgVar = fjvg.a;
        zVar.b("gads:app_index:timeout_ms", fjvgVar.a().a());
        zVar.d("gads:app_index:without_content_info_present:enabled", fjvgVar.a().b());
        fjxu.a.a().c();
        fjxu fjxuVar = fjxu.a;
        zVar.d("gads:ad_key_enabled", fjxuVar.a().a());
        zVar.d("gads:adshield:enable_adshield_instrumentation", fjxuVar.a().b());
        fjym.a.a().c();
        fjym fjymVar = fjym.a;
        zVar.d("gads:rewarded_sku:enabled", fjymVar.a().a());
        zVar.d("gads:rewarded_sku:override_test:enabled", fjymVar.a().b());
        fjyp.a.a().c();
        fjyp fjypVar = fjyp.a;
        zVar.c("gads:safe_browsing:api_key", fjypVar.a().a());
        zVar.d("gads:safe_browsing:debug", fjypVar.a().b());
        fjyv.a.a().d();
        fjyv fjyvVar = fjyv.a;
        zVar.c("gads:native:engine_js_url_with_protocol", fjyvVar.a().a());
        zVar.c("gads:sdk_core_location", fjyvVar.a().b());
        zVar.c("gads:sdk_core_js_location", fjyvVar.a().c());
        fjzt.a.a().b();
        zVar.d("gads:webview:permission:disabled", fjzt.a.a().a());
        fjvm.a.a().c();
        fjvm fjvmVar = fjvm.a;
        zVar.d("gads:auto_location_by_dynamite", fjvmVar.a().a());
        zVar.d("gads:auto_location_by_gmscore", fjvmVar.a().b());
        fjxi.a.a().c();
        zVar.d("gads:split_ad_request_traffic_by_app", fjxi.c());
        zVar.d("gads:split_doritos_traffic_from_ads_tag", fjxi.a.a().b());
        fjxo.a.a().d();
        fjxo fjxoVar = fjxo.a;
        zVar.d("gads:lite_sdk_retriever:adapter:enable", fjxoVar.a().b());
        zVar.b("gads:lite_sdk_retriever:dynamite_version", fjxoVar.a().a());
        zVar.d("gads:lite_sdk_retriever:version_number:enable", fjxoVar.a().c());
        fjze.a.a().b();
        zVar.d("gads:signals_collection_on_service:enabled", fjze.a.a().a());
        fjzn.a.a().i();
        fjzn fjznVar = fjzn.a;
        zVar.d("gads:trustless_token_for_decagon:enabled", fjznVar.a().d());
        zVar.d("gads:invalidate_token_at_refresh_start", fjznVar.a().e());
        zVar.d("gms:expose_token_for_gma:enabled", fjzn.e());
        zVar.d("gads:referesh_rate_limit", fjzn.f());
        zVar.b("gads:timeout_for_trustless_token:millis", fjznVar.a().a());
        zVar.d("gads:token_anonymization:enabled", fjzn.g());
        zVar.c("gads:token_anonymization_key", fjzn.d());
        zVar.b("gads:cached_token:ttl_millis", fjzn.b());
        fjwh.a.a().f();
        fjwh fjwhVar = fjwh.a;
        zVar.a("gads:cui_monitoring_session_sample_rate", fjwhVar.a().a());
        zVar.d("gads:cui_monitoring_enabled", fjwhVar.a().b());
        zVar.d("gads:cui_monitoring_v2_enabled", fjwhVar.a().c());
        zVar.d("gads:cui_monitoring_v3_enabled", fjwhVar.a().d());
        zVar.d("gads:cui_monitoring_v4_enabled", fjwhVar.a().e());
        fjvj.a.a().c();
        fjvj fjvjVar = fjvj.a;
        zVar.d("gads:timeout_for_app_set_id_info_gmscore:enabled", fjvjVar.a().b());
        zVar.b("gads:timeout_for_app_set_id_info_gmscore:millis", fjvjVar.a().a());
        fjya.a.a().i();
        fjya fjyaVar = fjya.a;
        zVar.d("gads:delegating_web_view_client_recursion_detection:enabled", fjyaVar.a().d());
        zVar.d("gads:paw_app_signals:document_start_js:enabled", fjyaVar.a().e());
        zVar.d("gads:paw_app_signals:enabled", fjyaVar.a().f());
        zVar.d("gads:paw_delegate_web_view_client:enabled", fjyaVar.a().g());
        zVar.d("gads:paw_cache:enabled", fjyaVar.a().h());
        zVar.b("gads:paw_cache:refresh_interval_seconds", fjyaVar.a().a());
        zVar.b("gads:paw_cache:retry_delay_seconds", fjyaVar.a().b());
        zVar.b("gads:paw_cache:ttl_ms", fjyaVar.a().c());
        fjyy.a.a().b();
        zVar.b("gads:minimum_service:version", fjyy.a.a().a());
    }
}
