package com.google.android.gms.ads.internal.request;

import android.content.pm.ApplicationInfo;
import android.content.pm.PackageInfo;
import android.os.Bundle;
import android.os.Parcel;
import android.os.Parcelable;
import com.google.android.gms.ads.internal.client.AdRequestParcel;
import com.google.android.gms.ads.internal.client.AdSizeParcel;
import com.google.android.gms.ads.internal.client.IconAdOptionsParcel;
import com.google.android.gms.ads.internal.formats.NativeAdOptionsParcel;
import com.google.android.gms.ads.internal.instream.InstreamAdConfigurationParcel;
import com.google.android.gms.ads.internal.util.client.VersionInfoParcel;
import com.google.android.gms.common.internal.safeparcel.AbstractSafeParcelable;
import defpackage.arxc;
import j$.util.DesugarCollections;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

/* compiled from: :com.google.android.gms@251661004@25.16.61 (040400-752466036) */
/* loaded from: classes2.dex */
public final class AdRequestInfoParcel extends AbstractSafeParcelable {
    public static final Parcelable.Creator CREATOR = new a();
    public final long A;
    public final String B;
    public final float C;
    public final int D;
    public final int E;
    public final boolean F;
    public final String G;
    public final boolean H;
    public final String I;
    public final boolean J;
    public final int K;
    public final Bundle L;
    public final String M;
    public final IconAdOptionsParcel N;
    public final boolean O;
    public final Bundle P;
    public final String Q;
    public final String R;
    public final String S;
    public final boolean T;
    public final List U;
    public final String V;
    public final List W;
    public final int X;
    public final boolean Y;
    public final boolean Z;
    public final int a;
    public final boolean aa;
    public final ArrayList ab;
    public final String ac;
    public final InstreamAdConfigurationParcel ad;
    public final String ae;
    public final Bundle af;
    public final Bundle b;
    public final AdRequestParcel c;
    public final AdSizeParcel d;
    public final String e;
    public final ApplicationInfo f;
    public final PackageInfo g;
    public final String h;
    public final String i;
    public final String j;
    public final VersionInfoParcel k;
    public final Bundle l;
    public final int m;
    public final List n;
    public final Bundle o;
    public final boolean p;
    public final int q;
    public final int r;
    public final float s;
    public final String t;
    public final long u;
    public final String v;
    public final List w;
    public final String x;
    public final NativeAdOptionsParcel y;
    public final List z;

    public AdRequestInfoParcel(int i, Bundle bundle, AdRequestParcel adRequestParcel, AdSizeParcel adSizeParcel, String str, ApplicationInfo applicationInfo, PackageInfo packageInfo, String str2, String str3, String str4, VersionInfoParcel versionInfoParcel, Bundle bundle2, int i2, List list, Bundle bundle3, boolean z, int i3, int i4, float f, String str5, long j, String str6, List list2, String str7, NativeAdOptionsParcel nativeAdOptionsParcel, List list3, long j2, String str8, float f2, boolean z2, int i5, int i6, boolean z3, String str9, String str10, boolean z4, int i7, Bundle bundle4, String str11, IconAdOptionsParcel iconAdOptionsParcel, boolean z5, Bundle bundle5, String str12, String str13, String str14, boolean z6, List list4, String str15, List list5, int i8, boolean z7, boolean z8, boolean z9, ArrayList arrayList, String str16, InstreamAdConfigurationParcel instreamAdConfigurationParcel, String str17, Bundle bundle6) {
        this.a = i;
        this.b = bundle;
        this.c = adRequestParcel;
        this.d = adSizeParcel;
        this.e = str;
        this.f = applicationInfo;
        this.g = packageInfo;
        this.h = str2;
        this.i = str3;
        this.j = str4;
        this.k = versionInfoParcel;
        this.l = bundle2;
        this.m = i2;
        this.n = list;
        this.z = list3 == null ? Collections.EMPTY_LIST : DesugarCollections.unmodifiableList(list3);
        this.o = bundle3;
        this.p = z;
        this.q = i3;
        this.r = i4;
        this.s = f;
        this.t = str5;
        this.u = j;
        this.v = str6;
        this.w = list2 == null ? Collections.EMPTY_LIST : DesugarCollections.unmodifiableList(list2);
        this.x = str7;
        this.y = nativeAdOptionsParcel;
        this.A = j2;
        this.B = str8;
        this.C = f2;
        this.H = z2;
        this.D = i5;
        this.E = i6;
        this.F = z3;
        this.G = str9;
        this.I = str10;
        this.J = z4;
        this.K = i7;
        this.L = bundle4;
        this.M = str11;
        this.N = iconAdOptionsParcel;
        this.O = z5;
        this.P = bundle5;
        this.Q = str12;
        this.R = str13;
        this.S = str14;
        this.T = z6;
        this.U = list4;
        this.V = str15;
        this.W = list5;
        this.X = i8;
        this.Y = z7;
        this.Z = z8;
        this.aa = z9;
        this.ab = arrayList;
        this.ac = str16;
        this.ad = instreamAdConfigurationParcel;
        this.ae = str17;
        this.af = bundle6;
    }

    @Override // android.os.Parcelable
    public final void writeToParcel(Parcel parcel, int i) {
        int a = arxc.a(parcel);
        arxc.o(parcel, 1, this.a);
        arxc.g(parcel, 2, this.b, false);
        arxc.t(parcel, 3, this.c, i, false);
        arxc.t(parcel, 4, this.d, i, false);
        arxc.v(parcel, 5, this.e, false);
        arxc.t(parcel, 6, this.f, i, false);
        arxc.t(parcel, 7, this.g, i, false);
        arxc.v(parcel, 8, this.h, false);
        arxc.v(parcel, 9, this.i, false);
        arxc.v(parcel, 10, this.j, false);
        arxc.t(parcel, 11, this.k, i, false);
        arxc.g(parcel, 12, this.l, false);
        arxc.o(parcel, 13, this.m);
        arxc.x(parcel, 14, this.n, false);
        arxc.g(parcel, 15, this.o, false);
        arxc.e(parcel, 16, this.p);
        arxc.o(parcel, 18, this.q);
        arxc.o(parcel, 19, this.r);
        arxc.l(parcel, 20, this.s);
        arxc.v(parcel, 21, this.t, false);
        arxc.q(parcel, 25, this.u);
        arxc.v(parcel, 26, this.v, false);
        arxc.x(parcel, 27, this.w, false);
        arxc.v(parcel, 28, this.x, false);
        arxc.t(parcel, 29, this.y, i, false);
        arxc.x(parcel, 30, this.z, false);
        arxc.q(parcel, 31, this.A);
        arxc.v(parcel, 33, this.B, false);
        arxc.l(parcel, 34, this.C);
        arxc.o(parcel, 35, this.D);
        arxc.o(parcel, 36, this.E);
        arxc.e(parcel, 37, this.F);
        arxc.v(parcel, 39, this.G, false);
        arxc.e(parcel, 40, this.H);
        arxc.v(parcel, 41, this.I, false);
        arxc.e(parcel, 42, this.J);
        arxc.o(parcel, 43, this.K);
        arxc.g(parcel, 44, this.L, false);
        arxc.v(parcel, 45, this.M, false);
        arxc.t(parcel, 46, this.N, i, false);
        arxc.e(parcel, 47, this.O);
        arxc.g(parcel, 48, this.P, false);
        arxc.v(parcel, 49, this.Q, false);
        arxc.v(parcel, 50, this.R, false);
        arxc.v(parcel, 51, this.S, false);
        arxc.e(parcel, 52, this.T);
        arxc.E(parcel, 53, this.U);
        arxc.v(parcel, 54, this.V, false);
        arxc.x(parcel, 55, this.W, false);
        arxc.o(parcel, 56, this.X);
        arxc.e(parcel, 57, this.Y);
        arxc.e(parcel, 58, this.Z);
        arxc.e(parcel, 59, this.aa);
        arxc.x(parcel, 60, this.ab, false);
        arxc.v(parcel, 61, this.ac, false);
        arxc.t(parcel, 63, this.ad, i, false);
        arxc.v(parcel, 64, this.ae, false);
        arxc.g(parcel, 65, this.af, false);
        arxc.c(parcel, a);
    }
}
