package com.google.android.gms.games.internal.player;

import android.os.Parcel;
import android.os.Parcelable;
import com.google.android.gms.games.internal.GamesAbstractSafeParcelable;
import defpackage.atyp;
import defpackage.atzr;
import defpackage.bjuc;
import java.util.ArrayList;
import java.util.Arrays;

/* compiled from: :com.google.android.gms@251864004@25.18.64 (040400-758020094) */
/* loaded from: classes4.dex */
public final class ProfileCapabilities extends GamesAbstractSafeParcelable {
    public static final Parcelable.Creator CREATOR = new bjuc();
    public final boolean a;
    public final boolean b;
    public final boolean c;
    public final boolean d;
    public final boolean e;
    public final boolean f;
    public final boolean g;
    public final boolean h;
    public final boolean i;
    public final boolean j;

    public ProfileCapabilities(boolean z, boolean z2, boolean z3, boolean z4, boolean z5, boolean z6, boolean z7, boolean z8, boolean z9, boolean z10) {
        this.a = z;
        this.b = z2;
        this.c = z3;
        this.d = z4;
        this.e = z5;
        this.f = z6;
        this.g = z7;
        this.h = z8;
        this.i = z9;
        this.j = z10;
    }

    public final boolean equals(Object obj) {
        if (!(obj instanceof ProfileCapabilities)) {
            return false;
        }
        if (this == obj) {
            return true;
        }
        ProfileCapabilities profileCapabilities = (ProfileCapabilities) obj;
        return this.a == profileCapabilities.a && this.b == profileCapabilities.b && this.c == profileCapabilities.c && this.d == profileCapabilities.d && this.e == profileCapabilities.e && this.f == profileCapabilities.f && this.g == profileCapabilities.g && this.h == profileCapabilities.h && this.i == profileCapabilities.i && this.j == profileCapabilities.j;
    }

    public final int hashCode() {
        return Arrays.hashCode(new Object[]{Boolean.valueOf(this.a), Boolean.valueOf(this.b), Boolean.valueOf(this.c), Boolean.valueOf(this.d), Boolean.valueOf(this.e), Boolean.valueOf(this.f), Boolean.valueOf(this.g), Boolean.valueOf(this.h), Boolean.valueOf(this.i), Boolean.valueOf(this.j)});
    }

    public final String toString() {
        ArrayList arrayList = new ArrayList();
        atyp.b("forbiddenToHavePlayerProfile", Boolean.valueOf(this.a), arrayList);
        atyp.b("requiresParentPermissionToShareData", Boolean.valueOf(this.b), arrayList);
        atyp.b("hasSettingsControlledByParent", Boolean.valueOf(this.c), arrayList);
        atyp.b("requiresParentPermissionToUsePlayTogether", Boolean.valueOf(this.d), arrayList);
        atyp.b("canUseOnlyAutoGeneratedGamerTag", Boolean.valueOf(this.e), arrayList);
        atyp.b("forbiddenToRecordVideo", Boolean.valueOf(this.f), arrayList);
        atyp.b("shouldSeeEquallyWeightedButtonsInConsents", Boolean.valueOf(this.g), arrayList);
        atyp.b("requiresParentConsentToUseAutoSignIn", Boolean.valueOf(this.h), arrayList);
        atyp.b("shouldSeeSimplifiedConsentMessages", Boolean.valueOf(this.i), arrayList);
        atyp.b("forbiddenToUseProfilelessRecall", Boolean.valueOf(this.j), arrayList);
        return atyp.a(arrayList, this);
    }

    @Override // android.os.Parcelable
    public final void writeToParcel(Parcel parcel, int i) {
        boolean z = this.a;
        int a = atzr.a(parcel);
        atzr.e(parcel, 1, z);
        atzr.e(parcel, 2, this.b);
        atzr.e(parcel, 3, this.c);
        atzr.e(parcel, 4, this.d);
        atzr.e(parcel, 5, this.e);
        atzr.e(parcel, 6, this.f);
        atzr.e(parcel, 7, this.g);
        atzr.e(parcel, 8, this.h);
        atzr.e(parcel, 9, this.i);
        atzr.e(parcel, 10, this.j);
        atzr.c(parcel, a);
    }
}
